<?php

use Illuminate\Database\Seeder;
use App\Models\Dashboard\Ciudades;

class CiudadesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Ciudades::create(['nombre_ciudad' => 'Cuenca', 'provincia_id' => '1' ]);
        Ciudades::create(['nombre_ciudad' => 'Gualaceo', 'provincia_id' => '1' ]);
        Ciudades::create(['nombre_ciudad' => 'Paute', 'provincia_id' => '1' ]);
        Ciudades::create(['nombre_ciudad' => 'Santa Isabel', 'provincia_id' => '1' ]);
        Ciudades::create(['nombre_ciudad' => 'Camilo Ponce Enríquez', 'provincia_id' => '1' ]);
        Ciudades::create(['nombre_ciudad' => 'Chordeleg', 'provincia_id' => '1' ]);
        Ciudades::create(['nombre_ciudad' => 'Girón', 'provincia_id' => '1' ]);
        Ciudades::create(['nombre_ciudad' => 'Sígsig', 'provincia_id' => '1' ]);
        Ciudades::create(['nombre_ciudad' => 'San Fernando', 'provincia_id' => '1' ]);
        Ciudades::create(['nombre_ciudad' => 'Nabón', 'provincia_id' => '1' ]);
        Ciudades::create(['nombre_ciudad' => 'Guachapala', 'provincia_id' => '1' ]);
        Ciudades::create(['nombre_ciudad' => 'Pucará', 'provincia_id' => '1' ]);
        Ciudades::create(['nombre_ciudad' => 'Oña', 'provincia_id' => '1' ]);
        Ciudades::create(['nombre_ciudad' => 'Sevilla de Oro', 'provincia_id' => '1' ]);
        Ciudades::create(['nombre_ciudad' => 'El Pan', 'provincia_id' => '1' ]);
        Ciudades::create(['nombre_ciudad' => 'Guaranda', 'provincia_id' => '2' ]);
        Ciudades::create(['nombre_ciudad' => 'San Miguel', 'provincia_id' => '2' ]);
        Ciudades::create(['nombre_ciudad' => 'Caluma', 'provincia_id' => '2' ]);
        Ciudades::create(['nombre_ciudad' => 'Echeandía', 'provincia_id' => '2' ]);
        Ciudades::create(['nombre_ciudad' => 'Chimbo', 'provincia_id' => '2' ]);
        Ciudades::create(['nombre_ciudad' => 'Chillanes', 'provincia_id' => '2' ]);
        Ciudades::create(['nombre_ciudad' => 'Las Naves', 'provincia_id' => '2' ]);
        Ciudades::create(['nombre_ciudad' => 'La Troncal', 'provincia_id' => '3' ]);
        Ciudades::create(['nombre_ciudad' => 'Azogues', 'provincia_id' => '3' ]);
        Ciudades::create(['nombre_ciudad' => 'Cañar', 'provincia_id' => '3' ]);
        Ciudades::create(['nombre_ciudad' => 'Biblián', 'provincia_id' => '3' ]);
        Ciudades::create(['nombre_ciudad' => 'El Tambo', 'provincia_id' => '3' ]);
        Ciudades::create(['nombre_ciudad' => 'Suscal', 'provincia_id' => '3' ]);
        Ciudades::create(['nombre_ciudad' => 'Déleg', 'provincia_id' => '3' ]);
        Ciudades::create(['nombre_ciudad' => 'Tulcán', 'provincia_id' => '4' ]);
        Ciudades::create(['nombre_ciudad' => 'San Gabriel', 'provincia_id' => '4' ]);
        Ciudades::create(['nombre_ciudad' => 'El Ángel', 'provincia_id' => '4' ]);
        Ciudades::create(['nombre_ciudad' => 'Huaca', 'provincia_id' => '4' ]);
        Ciudades::create(['nombre_ciudad' => 'Mira', 'provincia_id' => '4' ]);
        Ciudades::create(['nombre_ciudad' => 'Bolívar', 'provincia_id' => '4' ]);
        Ciudades::create(['nombre_ciudad' => 'Riobamba', 'provincia_id' => '5' ]);
        Ciudades::create(['nombre_ciudad' => 'Cumandá', 'provincia_id' => '5' ]);
        Ciudades::create(['nombre_ciudad' => 'Guano', 'provincia_id' => '5' ]);
        Ciudades::create(['nombre_ciudad' => 'Alausí', 'provincia_id' => '5' ]);
        Ciudades::create(['nombre_ciudad' => 'Chambo', 'provincia_id' => '5' ]);
        Ciudades::create(['nombre_ciudad' => 'Chunchi', 'provincia_id' => '5' ]);
        Ciudades::create(['nombre_ciudad' => 'Pallatanga', 'provincia_id' => '5' ]);
        Ciudades::create(['nombre_ciudad' => 'Guamote', 'provincia_id' => '5' ]);
        Ciudades::create(['nombre_ciudad' => 'Villa La Unión (Cajabamba)', 'provincia_id' => '5' ]);
        Ciudades::create(['nombre_ciudad' => 'Penipe', 'provincia_id' => '5' ]);
        Ciudades::create(['nombre_ciudad' => 'Latacunga', 'provincia_id' => '6' ]);
        Ciudades::create(['nombre_ciudad' => 'La Maná', 'provincia_id' => '6' ]);
        Ciudades::create(['nombre_ciudad' => 'San Miguel de Salcedo', 'provincia_id' => '6' ]);
        Ciudades::create(['nombre_ciudad' => 'Pujilí', 'provincia_id' => '6' ]);
        Ciudades::create(['nombre_ciudad' => 'Saquisilí', 'provincia_id' => '6' ]);
        Ciudades::create(['nombre_ciudad' => 'Sigchos', 'provincia_id' => '6' ]);
        Ciudades::create(['nombre_ciudad' => 'El Corazón', 'provincia_id' => '6' ]);
        Ciudades::create(['nombre_ciudad' => 'Machala', 'provincia_id' => '7' ]);
        Ciudades::create(['nombre_ciudad' => 'Pasaje', 'provincia_id' => '7' ]);
        Ciudades::create(['nombre_ciudad' => 'Santa Rosa', 'provincia_id' => '7' ]);
        Ciudades::create(['nombre_ciudad' => 'Huaquillas', 'provincia_id' => '7' ]);
        Ciudades::create(['nombre_ciudad' => 'El Guabo', 'provincia_id' => '7' ]);
        Ciudades::create(['nombre_ciudad' => 'Arenillas', 'provincia_id' => '7' ]);
        Ciudades::create(['nombre_ciudad' => 'Piñas', 'provincia_id' => '7' ]);
        Ciudades::create(['nombre_ciudad' => 'Zaruma', 'provincia_id' => '7' ]);
        Ciudades::create(['nombre_ciudad' => 'Portovelo', 'provincia_id' => '7' ]);
        Ciudades::create(['nombre_ciudad' => 'Balsas', 'provincia_id' => '7' ]);
        Ciudades::create(['nombre_ciudad' => 'Marcabelí', 'provincia_id' => '7' ]);
        Ciudades::create(['nombre_ciudad' => 'Paccha', 'provincia_id' => '7' ]);
        Ciudades::create(['nombre_ciudad' => 'La Victoria', 'provincia_id' => '7' ]);
        Ciudades::create(['nombre_ciudad' => 'Chilla', 'provincia_id' => '7' ]);
        Ciudades::create(['nombre_ciudad' => 'Esmeraldas', 'provincia_id' => '8' ]);
        Ciudades::create(['nombre_ciudad' => 'Rosa Zárate', 'provincia_id' => '8' ]);
        Ciudades::create(['nombre_ciudad' => 'San Lorenzo', 'provincia_id' => '8' ]);
        Ciudades::create(['nombre_ciudad' => 'Atacames', 'provincia_id' => '8' ]);
        Ciudades::create(['nombre_ciudad' => 'Muisne', 'provincia_id' => '8' ]);
        Ciudades::create(['nombre_ciudad' => 'Valdez (Limones)', 'provincia_id' => '8' ]);
        Ciudades::create(['nombre_ciudad' => 'Rioverde', 'provincia_id' => '8' ]);
        Ciudades::create(['nombre_ciudad' => 'Puerto Ayora', 'provincia_id' => '9' ]);
        Ciudades::create(['nombre_ciudad' => 'Puerto Baquerizo Moreno', 'provincia_id' => '9' ]);
        Ciudades::create(['nombre_ciudad' => 'Puerto Villamil', 'provincia_id' => '9' ]);
        Ciudades::create(['nombre_ciudad' => 'Guayaquil', 'provincia_id' => '10' ]);
        Ciudades::create(['nombre_ciudad' => 'Durán', 'provincia_id' => '10' ]);
        Ciudades::create(['nombre_ciudad' => 'Milagro', 'provincia_id' => '10' ]);
        Ciudades::create(['nombre_ciudad' => 'Daule', 'provincia_id' => '10' ]);
        Ciudades::create(['nombre_ciudad' => 'Samborondón', 'provincia_id' => '10' ]);
        Ciudades::create(['nombre_ciudad' => 'Velasco Ibarra', 'provincia_id' => '10' ]);
        Ciudades::create(['nombre_ciudad' => 'El Triunfo', 'provincia_id' => '10' ]);
        Ciudades::create(['nombre_ciudad' => 'General Villamil', 'provincia_id' => '10' ]);
        Ciudades::create(['nombre_ciudad' => 'Balzar', 'provincia_id' => '10' ]);
        Ciudades::create(['nombre_ciudad' => 'Naranjito', 'provincia_id' => '10' ]);
        Ciudades::create(['nombre_ciudad' => 'Naranjal', 'provincia_id' => '10' ]);
        Ciudades::create(['nombre_ciudad' => 'Pedro Carbo', 'provincia_id' => '10' ]);
        Ciudades::create(['nombre_ciudad' => 'Yaguachi', 'provincia_id' => '10' ]);
        Ciudades::create(['nombre_ciudad' => 'Lomas de Sargentillo', 'provincia_id' => '10' ]);
        Ciudades::create(['nombre_ciudad' => 'Salitre', 'provincia_id' => '10' ]);
        Ciudades::create(['nombre_ciudad' => 'Balao', 'provincia_id' => '10' ]);
        Ciudades::create(['nombre_ciudad' => 'Santa Lucía', 'provincia_id' => '10' ]);
        Ciudades::create(['nombre_ciudad' => 'Palestina', 'provincia_id' => '10' ]);
        Ciudades::create(['nombre_ciudad' => 'Alfredo Baquerizo Moreno', 'provincia_id' => '10' ]);
        Ciudades::create(['nombre_ciudad' => 'Nobol', 'provincia_id' => '10' ]);
        Ciudades::create(['nombre_ciudad' => 'Simón Bolívar', 'provincia_id' => '10' ]);
        Ciudades::create(['nombre_ciudad' => 'Cnel. Marcelino Maridueña', 'provincia_id' => '10' ]);
        Ciudades::create(['nombre_ciudad' => 'Colimes', 'provincia_id' => '10' ]);
        Ciudades::create(['nombre_ciudad' => 'Gral. Antonio Elizalde (Bucay)', 'provincia_id' => '10' ]);
        Ciudades::create(['nombre_ciudad' => 'Isidro Ayora', 'provincia_id' => '10' ]);
        Ciudades::create(['nombre_ciudad' => 'Ibarra', 'provincia_id' => '11' ]);
        Ciudades::create(['nombre_ciudad' => 'Otavalo', 'provincia_id' => '11' ]);
        Ciudades::create(['nombre_ciudad' => 'Atuntaqui', 'provincia_id' => '11' ]);
        Ciudades::create(['nombre_ciudad' => 'Cotacachi', 'provincia_id' => '11' ]);
        Ciudades::create(['nombre_ciudad' => 'Pimampiro', 'provincia_id' => '11' ]);
        Ciudades::create(['nombre_ciudad' => 'Urcuquí', 'provincia_id' => '11' ]);
        Ciudades::create(['nombre_ciudad' => 'Loja', 'provincia_id' => '12' ]);
        Ciudades::create(['nombre_ciudad' => 'Catamayo', 'provincia_id' => '12' ]);
        Ciudades::create(['nombre_ciudad' => 'Cariamanga', 'provincia_id' => '12' ]);
        Ciudades::create(['nombre_ciudad' => 'Macará', 'provincia_id' => '12' ]);
        Ciudades::create(['nombre_ciudad' => 'Catacocha', 'provincia_id' => '12' ]);
        Ciudades::create(['nombre_ciudad' => 'Alamor', 'provincia_id' => '12' ]);
        Ciudades::create(['nombre_ciudad' => 'Celica', 'provincia_id' => '12' ]);
        Ciudades::create(['nombre_ciudad' => 'Saraguro', 'provincia_id' => '12' ]);
        Ciudades::create(['nombre_ciudad' => 'Zapotillo', 'provincia_id' => '12' ]);
        Ciudades::create(['nombre_ciudad' => 'Pindal', 'provincia_id' => '12' ]);
        Ciudades::create(['nombre_ciudad' => 'Amaluza', 'provincia_id' => '12' ]);
        Ciudades::create(['nombre_ciudad' => 'Gonzanamá', 'provincia_id' => '12' ]);
        Ciudades::create(['nombre_ciudad' => 'Chaguarpamba', 'provincia_id' => '12' ]);
        Ciudades::create(['nombre_ciudad' => 'Sozoranga', 'provincia_id' => '12' ]);
        Ciudades::create(['nombre_ciudad' => 'Quilanga', 'provincia_id' => '12' ]);
        Ciudades::create(['nombre_ciudad' => 'Olmedo', 'provincia_id' => '12' ]);
        Ciudades::create(['nombre_ciudad' => 'Quevedo', 'provincia_id' => '13' ]);
        Ciudades::create(['nombre_ciudad' => 'Babahoyo', 'provincia_id' => '13' ]);
        Ciudades::create(['nombre_ciudad' => 'Buena Fe', 'provincia_id' => '13' ]);
        Ciudades::create(['nombre_ciudad' => 'Ventanas', 'provincia_id' => '13' ]);
        Ciudades::create(['nombre_ciudad' => 'Vinces', 'provincia_id' => '13' ]);
        Ciudades::create(['nombre_ciudad' => 'Valencia', 'provincia_id' => '13' ]);
        Ciudades::create(['nombre_ciudad' => 'Montalvo', 'provincia_id' => '13' ]);
        Ciudades::create(['nombre_ciudad' => 'Mocache', 'provincia_id' => '13' ]);
        Ciudades::create(['nombre_ciudad' => 'Puebloviejo', 'provincia_id' => '13' ]);
        Ciudades::create(['nombre_ciudad' => 'Palenque', 'provincia_id' => '13' ]);
        Ciudades::create(['nombre_ciudad' => 'Catarama', 'provincia_id' => '13' ]);
        Ciudades::create(['nombre_ciudad' => 'Baba', 'provincia_id' => '13' ]);
        Ciudades::create(['nombre_ciudad' => 'Quinsaloma', 'provincia_id' => '13' ]);
        Ciudades::create(['nombre_ciudad' => 'Manta', 'provincia_id' => '14' ]);
        Ciudades::create(['nombre_ciudad' => 'Portoviejo', 'provincia_id' => '14' ]);
        Ciudades::create(['nombre_ciudad' => 'Chone', 'provincia_id' => '14' ]);
        Ciudades::create(['nombre_ciudad' => 'El Carmen', 'provincia_id' => '14' ]);
        Ciudades::create(['nombre_ciudad' => 'Montecristi', 'provincia_id' => '14' ]);
        Ciudades::create(['nombre_ciudad' => 'Jipijapa', 'provincia_id' => '14' ]);
        Ciudades::create(['nombre_ciudad' => 'Pedernales', 'provincia_id' => '14' ]);
        Ciudades::create(['nombre_ciudad' => 'Bahía de Caráquez', 'provincia_id' => '14' ]);
        Ciudades::create(['nombre_ciudad' => 'Calceta', 'provincia_id' => '14' ]);
        Ciudades::create(['nombre_ciudad' => 'Jaramijó', 'provincia_id' => '14' ]);
        Ciudades::create(['nombre_ciudad' => 'Tosagua', 'provincia_id' => '14' ]);
        Ciudades::create(['nombre_ciudad' => 'Puerto López', 'provincia_id' => '14' ]);
        Ciudades::create(['nombre_ciudad' => 'San Vicente', 'provincia_id' => '14' ]);
        Ciudades::create(['nombre_ciudad' => 'Santa Ana', 'provincia_id' => '14' ]);
        Ciudades::create(['nombre_ciudad' => 'Rocafuerte', 'provincia_id' => '14' ]);
        Ciudades::create(['nombre_ciudad' => 'Paján', 'provincia_id' => '14' ]);
        Ciudades::create(['nombre_ciudad' => 'Flavio Alfaro', 'provincia_id' => '14' ]);
        Ciudades::create(['nombre_ciudad' => 'Jama', 'provincia_id' => '14' ]);
        Ciudades::create(['nombre_ciudad' => 'Junín', 'provincia_id' => '14' ]);
        Ciudades::create(['nombre_ciudad' => 'Pichincha', 'provincia_id' => '14' ]);
        Ciudades::create(['nombre_ciudad' => 'Sucre', 'provincia_id' => '14' ]);
        Ciudades::create(['nombre_ciudad' => 'Olmedo', 'provincia_id' => '14' ]);
        Ciudades::create(['nombre_ciudad' => 'Macas', 'provincia_id' => '15' ]);
        Ciudades::create(['nombre_ciudad' => 'Sucúa', 'provincia_id' => '15' ]);
        Ciudades::create(['nombre_ciudad' => 'Gualaquiza', 'provincia_id' => '15' ]);
        Ciudades::create(['nombre_ciudad' => 'Gral. Leonidas Plaza Gutiérrez (Limón)', 'provincia_id' => '15' ]);
        Ciudades::create(['nombre_ciudad' => 'Palora', 'provincia_id' => '15' ]);
        Ciudades::create(['nombre_ciudad' => 'Santiago de Méndez', 'provincia_id' => '15' ]);
        Ciudades::create(['nombre_ciudad' => 'Logroño', 'provincia_id' => '15' ]);
        Ciudades::create(['nombre_ciudad' => 'San Juan Bosco', 'provincia_id' => '15' ]);
        Ciudades::create(['nombre_ciudad' => 'Santiago', 'provincia_id' => '15' ]);
        Ciudades::create(['nombre_ciudad' => 'Taisha', 'provincia_id' => '15' ]);
        Ciudades::create(['nombre_ciudad' => 'Huamboya', 'provincia_id' => '15' ]);
        Ciudades::create(['nombre_ciudad' => 'Pablo Sexto', 'provincia_id' => '15' ]);
        Ciudades::create(['nombre_ciudad' => 'Tena', 'provincia_id' => '16' ]);
        Ciudades::create(['nombre_ciudad' => 'Archidona', 'provincia_id' => '16' ]);
        Ciudades::create(['nombre_ciudad' => 'El Chaco', 'provincia_id' => '16' ]);
        Ciudades::create(['nombre_ciudad' => 'Baeza', 'provincia_id' => '16' ]);
        Ciudades::create(['nombre_ciudad' => 'Carlos Julio Arosemena Tola', 'provincia_id' => '16' ]);
        Ciudades::create(['nombre_ciudad' => 'Puerto Francisco de Orellana', 'provincia_id' => '17' ]);
        Ciudades::create(['nombre_ciudad' => 'La Joya de los Sachas', 'provincia_id' => '17' ]);
        Ciudades::create(['nombre_ciudad' => 'Loreto', 'provincia_id' => '17' ]);
        Ciudades::create(['nombre_ciudad' => 'Tiputini', 'provincia_id' => '17' ]);
        Ciudades::create(['nombre_ciudad' => 'Puyo', 'provincia_id' => '18' ]);
        Ciudades::create(['nombre_ciudad' => 'Santa Clara', 'provincia_id' => '18' ]);
        Ciudades::create(['nombre_ciudad' => 'Arajuno', 'provincia_id' => '18' ]);
        Ciudades::create(['nombre_ciudad' => 'Mera', 'provincia_id' => '18' ]);
        Ciudades::create(['nombre_ciudad' => 'Quito', 'provincia_id' => '19' ]);
        Ciudades::create(['nombre_ciudad' => 'Sangolquí', 'provincia_id' => '19' ]);
        Ciudades::create(['nombre_ciudad' => 'Cayambe', 'provincia_id' => '19' ]);
        Ciudades::create(['nombre_ciudad' => 'Machachi', 'provincia_id' => '19' ]);
        Ciudades::create(['nombre_ciudad' => 'Tabacundo', 'provincia_id' => '19' ]);
        Ciudades::create(['nombre_ciudad' => 'Pedro Vicente Maldonado', 'provincia_id' => '19' ]);
        Ciudades::create(['nombre_ciudad' => 'San Miguel de Los Bancos', 'provincia_id' => '19' ]);
        Ciudades::create(['nombre_ciudad' => 'Puerto Quito', 'provincia_id' => '19' ]);
        Ciudades::create(['nombre_ciudad' => 'La Libertad', 'provincia_id' => '20' ]);
        Ciudades::create(['nombre_ciudad' => 'Santa Elena', 'provincia_id' => '20' ]);
        Ciudades::create(['nombre_ciudad' => 'Salinas', 'provincia_id' => '20' ]);
        Ciudades::create(['nombre_ciudad' => 'Santo Domingo', 'provincia_id' => '21' ]);
        Ciudades::create(['nombre_ciudad' => 'La Concordia', 'provincia_id' => '21' ]);
        Ciudades::create(['nombre_ciudad' => 'Nueva Loja', 'provincia_id' => '22' ]);
        Ciudades::create(['nombre_ciudad' => 'Shushufindi', 'provincia_id' => '22' ]);
        Ciudades::create(['nombre_ciudad' => 'Puerto El Carmen de Putumayo', 'provincia_id' => '22' ]);
        Ciudades::create(['nombre_ciudad' => 'El Dorado de Cascales', 'provincia_id' => '22' ]);
        Ciudades::create(['nombre_ciudad' => 'Lumbaqui', 'provincia_id' => '22' ]);
        Ciudades::create(['nombre_ciudad' => 'Tarapoa', 'provincia_id' => '22' ]);
        Ciudades::create(['nombre_ciudad' => 'La Bonita', 'provincia_id' => '22' ]);
        Ciudades::create(['nombre_ciudad' => 'Ambato', 'provincia_id' => '23' ]);
        Ciudades::create(['nombre_ciudad' => 'Baños de Agua Santa', 'provincia_id' => '23' ]);
        Ciudades::create(['nombre_ciudad' => 'Pelileo', 'provincia_id' => '23' ]);
        Ciudades::create(['nombre_ciudad' => 'Píllaro', 'provincia_id' => '23' ]);
        Ciudades::create(['nombre_ciudad' => 'Quero', 'provincia_id' => '23' ]);
        Ciudades::create(['nombre_ciudad' => 'Cevallos', 'provincia_id' => '23' ]);
        Ciudades::create(['nombre_ciudad' => 'Patate', 'provincia_id' => '23' ]);
        Ciudades::create(['nombre_ciudad' => 'Tisaleo', 'provincia_id' => '23' ]);
        Ciudades::create(['nombre_ciudad' => 'Mocha', 'provincia_id' => '23' ]);
        Ciudades::create(['nombre_ciudad' => 'Zamora', 'provincia_id' => '24' ]);
        Ciudades::create(['nombre_ciudad' => 'Yantzaza', 'provincia_id' => '24' ]);
        Ciudades::create(['nombre_ciudad' => 'Zumba', 'provincia_id' => '24' ]);
        Ciudades::create(['nombre_ciudad' => 'El Pangui', 'provincia_id' => '24' ]);
        Ciudades::create(['nombre_ciudad' => 'Zumbi', 'provincia_id' => '24' ]);
        Ciudades::create(['nombre_ciudad' => 'Palanda', 'provincia_id' => '24' ]);
        Ciudades::create(['nombre_ciudad' => 'Guayzimi', 'provincia_id' => '24' ]);
        Ciudades::create(['nombre_ciudad' => 'Yacuambi', 'provincia_id' => '24' ]);
        Ciudades::create(['nombre_ciudad' => 'Paquisha', 'provincia_id' => '24' ]);


    }
}
