<?php

use Illuminate\Database\Seeder;
use App\Models\Dashboard\Paises;

class PaisesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {        
        
        // $pais = Paises::create(['codigo_pais'=>'20','nombre_pais'=>'ANDORRA','alfa2'=>'AD','alfa3'=>'AND']);
        // $pais =Paises::create(['codigo_pais'=>'784','nombre_pais'=>'EMIRATOS ÁRABES UNIDOS','alfa2'=>'AE','alfa3'=>'ARE']);
        // $pais =Paises::create(['codigo_pais'=>'4','nombre_pais'=>'AFGANISTÁN','alfa2'=>'AF','alfa3'=>'AFG']);
        // $pais =Paises::create(['codigo_pais'=>'28','nombre_pais'=>'ANTIGUA Y BARBUDA','alfa2'=>'AG','alfa3'=>'ATG']);
        // $pais =Paises::create(['codigo_pais'=>'660','nombre_pais'=>'ANGUILA','alfa2'=>'AI','alfa3'=>'AIA']);
        // $pais =Paises::create(['codigo_pais'=>'8','nombre_pais'=>'ALBANIA','alfa2'=>'AL','alfa3'=>'ALB']);
        // $pais =Paises::create(['codigo_pais'=>'51','nombre_pais'=>'ARMENIA','alfa2'=>'AM','alfa3'=>'ARM']);
        // $pais =Paises::create(['codigo_pais'=>'530','nombre_pais'=>'ANTILLAS NEERLANDESAS','alfa2'=>'AN','alfa3'=>'ANT']);
        // $pais =Paises::create(['codigo_pais'=>'24','nombre_pais'=>'ANGOLA','alfa2'=>'AO','alfa3'=>'AGO']);
        // $pais =Paises::create(['codigo_pais'=>'10','nombre_pais'=>'ANTÁRTIDA','alfa2'=>'AQ','alfa3'=>'ATA']);
        // $pais =Paises::create(['codigo_pais'=>'32','nombre_pais'=>'ARGENTINA','alfa2'=>'AR','alfa3'=>'ARG']);
        // $pais =Paises::create(['codigo_pais'=>'16','nombre_pais'=>'SAMOA AMERICANA','alfa2'=>'AS','alfa3'=>'ASM']);
        // $pais =Paises::create(['codigo_pais'=>'40','nombre_pais'=>'AUSTRIA','alfa2'=>'AT','alfa3'=>'AUT']);
        // $pais =Paises::create(['codigo_pais'=>'36','nombre_pais'=>'AUSTRALIA','alfa2'=>'AU','alfa3'=>'AUS']);
        // $pais =Paises::create(['codigo_pais'=>'533','nombre_pais'=>'ARUBA','alfa2'=>'AW','alfa3'=>'ABW']);
        // $pais =Paises::create(['codigo_pais'=>'248','nombre_pais'=>'ISLAS ÁLAND','alfa2'=>'AX','alfa3'=>'ALA']);
        // $pais =Paises::create(['codigo_pais'=>'31','nombre_pais'=>'AZERBAIYÁN','alfa2'=>'AZ','alfa3'=>'AZE']);
        // $pais =Paises::create(['codigo_pais'=>'70','nombre_pais'=>'BOSNIA Y HERZEGOVINA','alfa2'=>'BA','alfa3'=>'BIH']);
        // $pais =Paises::create(['codigo_pais'=>'52','nombre_pais'=>'BARBADOS','alfa2'=>'BB','alfa3'=>'BRB']);
        // $pais =Paises::create(['codigo_pais'=>'50','nombre_pais'=>'BANGLADESH','alfa2'=>'BD','alfa3'=>'BGD']);
        // $pais =Paises::create(['codigo_pais'=>'56','nombre_pais'=>'BÉLGICA','alfa2'=>'BE','alfa3'=>'BEL']);
        // $pais =Paises::create(['codigo_pais'=>'854','nombre_pais'=>'BURKINA FASO','alfa2'=>'BF','alfa3'=>'BFA']);
        // $pais =Paises::create(['codigo_pais'=>'100','nombre_pais'=>'BULGARIA','alfa2'=>'BG','alfa3'=>'BGR']);
        // $pais =Paises::create(['codigo_pais'=>'48','nombre_pais'=>'BAHRÉIN','alfa2'=>'BH','alfa3'=>'BHR']);
        // $pais =Paises::create(['codigo_pais'=>'108','nombre_pais'=>'BURUNDI','alfa2'=>'BI','alfa3'=>'BDI']);
        // $pais =Paises::create(['codigo_pais'=>'204','nombre_pais'=>'BENIN','alfa2'=>'BJ','alfa3'=>'BEN']);
        // $pais =Paises::create(['codigo_pais'=>'652','nombre_pais'=>'SAN BARTOLOMÉ','alfa2'=>'BL','alfa3'=>'BLM']);
        // $pais =Paises::create(['codigo_pais'=>'60','nombre_pais'=>'BERMUDAS','alfa2'=>'BM','alfa3'=>'BMU']);
        // $pais =Paises::create(['codigo_pais'=>'96','nombre_pais'=>'BRUNÉI','alfa2'=>'BN','alfa3'=>'BRN']);
        // $pais =Paises::create(['codigo_pais'=>'68','nombre_pais'=>'BOLIVIA','alfa2'=>'BO','alfa3'=>'BOL']);
        // $pais =Paises::create(['codigo_pais'=>'76','nombre_pais'=>'BRASIL','alfa2'=>'BR','alfa3'=>'BRA']);
        // $pais =Paises::create(['codigo_pais'=>'44','nombre_pais'=>'BAHAMAS','alfa2'=>'BS','alfa3'=>'BHS']);
        // $pais =Paises::create(['codigo_pais'=>'64','nombre_pais'=>'BHUTÁN','alfa2'=>'BT','alfa3'=>'BTN']);
        // $pais =Paises::create(['codigo_pais'=>'74','nombre_pais'=>'ISLA BOUVET','alfa2'=>'BV','alfa3'=>'BVT']);
        // $pais =Paises::create(['codigo_pais'=>'72','nombre_pais'=>'BOTSUANA','alfa2'=>'BW','alfa3'=>'BWA']);
        // $pais =Paises::create(['codigo_pais'=>'112','nombre_pais'=>'BELARÚS','alfa2'=>'BY','alfa3'=>'BLR']);
        // $pais =Paises::create(['codigo_pais'=>'84','nombre_pais'=>'BELICE','alfa2'=>'BZ','alfa3'=>'BLZ']);
        // $pais =Paises::create(['codigo_pais'=>'124','nombre_pais'=>'CANADÁ','alfa2'=>'CA','alfa3'=>'CAN']);
        // $pais =Paises::create(['codigo_pais'=>'166','nombre_pais'=>'ISLAS COCOS','alfa2'=>'CC','alfa3'=>'CCK']);
        // $pais =Paises::create(['codigo_pais'=>'140','nombre_pais'=>'REPÚBLICA CENTRO-AFRICANA','alfa2'=>'CF','alfa3'=>'CAF']);
        // $pais =Paises::create(['codigo_pais'=>'178','nombre_pais'=>'CONGO','alfa2'=>'CG','alfa3'=>'COG']);
        // $pais =Paises::create(['codigo_pais'=>'756','nombre_pais'=>'SUIZA','alfa2'=>'CH','alfa3'=>'CHE']);
        // $pais =Paises::create(['codigo_pais'=>'384','nombre_pais'=>'COSTA DE MARFIL','alfa2'=>'CI','alfa3'=>'CIV']);
        // $pais =Paises::create(['codigo_pais'=>'184','nombre_pais'=>'ISLAS COOK','alfa2'=>'CK','alfa3'=>'COK']);
        // $pais =Paises::create(['codigo_pais'=>'152','nombre_pais'=>'CHILE','alfa2'=>'CL','alfa3'=>'CHL']);
        // $pais =Paises::create(['codigo_pais'=>'120','nombre_pais'=>'CAMERÚN','alfa2'=>'CM','alfa3'=>'CMR']);
        // $pais =Paises::create(['codigo_pais'=>'156','nombre_pais'=>'CHINA','alfa2'=>'CN','alfa3'=>'CHN']);
        // $pais =Paises::create(['codigo_pais'=>'170','nombre_pais'=>'COLOMBIA','alfa2'=>'CO','alfa3'=>'COL', 'idioma'=>'es']);
        // $pais =Paises::create(['codigo_pais'=>'188','nombre_pais'=>'COSTA RICA','alfa2'=>'CR','alfa3'=>'CRI']);
        // $pais =Paises::create(['codigo_pais'=>'192','nombre_pais'=>'CUBA','alfa2'=>'CU','alfa3'=>'CUB']);
        // $pais =Paises::create(['codigo_pais'=>'132','nombre_pais'=>'CABO VERDE','alfa2'=>'CV','alfa3'=>'CPV']);
        // $pais =Paises::create(['codigo_pais'=>'162','nombre_pais'=>'ISLAS CHRISTMAS','alfa2'=>'CX','alfa3'=>'CXR']);
        // $pais =Paises::create(['codigo_pais'=>'196','nombre_pais'=>'CHIPRE','alfa2'=>'CY','alfa3'=>'CYP']);
        // $pais =Paises::create(['codigo_pais'=>'203','nombre_pais'=>'REPÚBLICA CHECA','alfa2'=>'CZ','alfa3'=>'CZE']);
        // $pais =Paises::create(['codigo_pais'=>'276','nombre_pais'=>'ALEMANIA','alfa2'=>'DE','alfa3'=>'DEU']);
        // $pais =Paises::create(['codigo_pais'=>'262','nombre_pais'=>'YIBUTI','alfa2'=>'DJ','alfa3'=>'DJI']);
        // $pais =Paises::create(['codigo_pais'=>'208','nombre_pais'=>'DINAMARCA','alfa2'=>'DK','alfa3'=>'DNK']);
        // $pais =Paises::create(['codigo_pais'=>'212','nombre_pais'=>'DOMÍNICA','alfa2'=>'DM','alfa3'=>'DMA']);
        // $pais =Paises::create(['codigo_pais'=>'214','nombre_pais'=>'REPÚBLICA DOMINICANA','alfa2'=>'DO','alfa3'=>'DOM']);
        // $pais =Paises::create(['codigo_pais'=>'12','nombre_pais'=>'ARGEL','alfa2'=>'DZ','alfa3'=>'DZA']);
        $pais =Paises::create(['codigo_pais'=>'218','nombre_pais'=>'ECUADOR','alfa2'=>'EC','alfa3'=>'ECU']);
        // $pais =Paises::create(['codigo_pais'=>'233','nombre_pais'=>'ESTONIA','alfa2'=>'EE','alfa3'=>'EST']);
        // $pais =Paises::create(['codigo_pais'=>'818','nombre_pais'=>'EGIPTO','alfa2'=>'EG','alfa3'=>'EGY']);
        // $pais =Paises::create(['codigo_pais'=>'732','nombre_pais'=>'SAHARA OCCIDENTAL','alfa2'=>'EH','alfa3'=>'ESH']);
        // $pais =Paises::create(['codigo_pais'=>'232','nombre_pais'=>'ERITREA','alfa2'=>'ER','alfa3'=>'ERI']);
        // $pais =Paises::create(['codigo_pais'=>'724','nombre_pais'=>'ESPAÑA','alfa2'=>'ES','alfa3'=>'ESP']);
        // $pais =Paises::create(['codigo_pais'=>'231','nombre_pais'=>'ETIOPÍA','alfa2'=>'ET','alfa3'=>'ETH']);
        // $pais =Paises::create(['codigo_pais'=>'246','nombre_pais'=>'FINLANDIA','alfa2'=>'FI','alfa3'=>'FIN']);
        // $pais =Paises::create(['codigo_pais'=>'242','nombre_pais'=>'FIJI','alfa2'=>'FJ','alfa3'=>'FJI']);
        // $pais =Paises::create(['codigo_pais'=>'238','nombre_pais'=>'ISLAS MALVINAS','alfa2'=>'FK','alfa3'=>'KLK']);
        // $pais =Paises::create(['codigo_pais'=>'583','nombre_pais'=>'MICRONESIA','alfa2'=>'FM','alfa3'=>'FSM']);
        // $pais =Paises::create(['codigo_pais'=>'234','nombre_pais'=>'ISLAS FAROE','alfa2'=>'FO','alfa3'=>'FRO']);
        // $pais =Paises::create(['codigo_pais'=>'250','nombre_pais'=>'FRANCIA','alfa2'=>'FR','alfa3'=>'FRA']);
        // $pais =Paises::create(['codigo_pais'=>'266','nombre_pais'=>'GABÓN','alfa2'=>'GA','alfa3'=>'GAB']);
        // $pais =Paises::create(['codigo_pais'=>'826','nombre_pais'=>'REINO UNIDO','alfa2'=>'GB','alfa3'=>'GBR']);
        // $pais =Paises::create(['codigo_pais'=>'308','nombre_pais'=>'GRANADA','alfa2'=>'GD','alfa3'=>'GRD']);
        // $pais =Paises::create(['codigo_pais'=>'268','nombre_pais'=>'GEORGIA','alfa2'=>'GE','alfa3'=>'GEO']);
        // $pais =Paises::create(['codigo_pais'=>'254','nombre_pais'=>'GUAYANA FRANCESA','alfa2'=>'GF','alfa3'=>'GUF']);
        // $pais =Paises::create(['codigo_pais'=>'831','nombre_pais'=>'GUERNSEY','alfa2'=>'GG','alfa3'=>'GGY']);
        // $pais =Paises::create(['codigo_pais'=>'288','nombre_pais'=>'GHANA','alfa2'=>'GH','alfa3'=>'GHA']);
        // $pais =Paises::create(['codigo_pais'=>'292','nombre_pais'=>'GIBRALTAR','alfa2'=>'GI','alfa3'=>'GIB']);
        // $pais =Paises::create(['codigo_pais'=>'304','nombre_pais'=>'GROENLANDIA','alfa2'=>'GL','alfa3'=>'GRL']);
        // $pais =Paises::create(['codigo_pais'=>'270','nombre_pais'=>'GAMBIA','alfa2'=>'GM','alfa3'=>'GMB']);
        // $pais =Paises::create(['codigo_pais'=>'324','nombre_pais'=>'GUINEA','alfa2'=>'GN','alfa3'=>'GIN']);
        // $pais =Paises::create(['codigo_pais'=>'312','nombre_pais'=>'GUADALUPE','alfa2'=>'GP','alfa3'=>'GLP']);
        // $pais =Paises::create(['codigo_pais'=>'226','nombre_pais'=>'GUINEA ECUATORIAL','alfa2'=>'GQ','alfa3'=>'GNQ']);
        // $pais =Paises::create(['codigo_pais'=>'300','nombre_pais'=>'GRECIA','alfa2'=>'GR','alfa3'=>'GRC']);
        // $pais =Paises::create(['codigo_pais'=>'239','nombre_pais'=>'GEORGIA DEL SUR E ISLAS SANDWICH DEL SUR','alfa2'=>'GS','alfa3'=>'SGS']);
        // $pais =Paises::create(['codigo_pais'=>'320','nombre_pais'=>'GUATEMALA','alfa2'=>'GT','alfa3'=>'GTM']);
        // $pais =Paises::create(['codigo_pais'=>'316','nombre_pais'=>'GUAM','alfa2'=>'GU','alfa3'=>'GUM']);
        // $pais =Paises::create(['codigo_pais'=>'624','nombre_pais'=>'GUINEA-BISSAU','alfa2'=>'GW','alfa3'=>'GNB']);
        // $pais =Paises::create(['codigo_pais'=>'328','nombre_pais'=>'GUAYANA','alfa2'=>'GY','alfa3'=>'GUY']);
        // $pais =Paises::create(['codigo_pais'=>'344','nombre_pais'=>'HONG KONG','alfa2'=>'HK','alfa3'=>'HKG']);
        // $pais =Paises::create(['codigo_pais'=>'334','nombre_pais'=>'ISLAS HEARD Y MCDONALD','alfa2'=>'HM','alfa3'=>'HMD']);
        // $pais =Paises::create(['codigo_pais'=>'340','nombre_pais'=>'HONDURAS','alfa2'=>'HN','alfa3'=>'HND']);
        // $pais =Paises::create(['codigo_pais'=>'191','nombre_pais'=>'CROACIA','alfa2'=>'HR','alfa3'=>'HRV']);
        // $pais =Paises::create(['codigo_pais'=>'332','nombre_pais'=>'HAITÍ','alfa2'=>'HT','alfa3'=>'HTI']);
        // $pais =Paises::create(['codigo_pais'=>'348','nombre_pais'=>'HUNGRÍA','alfa2'=>'HU','alfa3'=>'HUN']);
        // $pais =Paises::create(['codigo_pais'=>'360','nombre_pais'=>'INDONESIA','alfa2'=>'ID','alfa3'=>'IDN']);
        // $pais =Paises::create(['codigo_pais'=>'372','nombre_pais'=>'IRLANDA','alfa2'=>'IE','alfa3'=>'IRL']);
        // $pais =Paises::create(['codigo_pais'=>'376','nombre_pais'=>'ISRAEL','alfa2'=>'IL','alfa3'=>'ISR']);
        // $pais =Paises::create(['codigo_pais'=>'833','nombre_pais'=>'ISLA DE MAN','alfa2'=>'IM','alfa3'=>'IMN']);
        // $pais =Paises::create(['codigo_pais'=>'356','nombre_pais'=>'INDIA','alfa2'=>'IN','alfa3'=>'IND']);
        // $pais =Paises::create(['codigo_pais'=>'86','nombre_pais'=>'TERRITORIO BRITÁNICO DEL OCÉANO ÍNDICO','alfa2'=>'IO','alfa3'=>'IOT']);
        // $pais =Paises::create(['codigo_pais'=>'368','nombre_pais'=>'IRAK','alfa2'=>'IQ','alfa3'=>'IRQ']);
        // $pais =Paises::create(['codigo_pais'=>'364','nombre_pais'=>'IRÁN','alfa2'=>'IR','alfa3'=>'IRN']);
        // $pais =Paises::create(['codigo_pais'=>'352','nombre_pais'=>'ISLANDIA','alfa2'=>'IS','alfa3'=>'ISL']);
        // $pais =Paises::create(['codigo_pais'=>'380','nombre_pais'=>'ITALIA','alfa2'=>'IT','alfa3'=>'ITA']);
        // $pais =Paises::create(['codigo_pais'=>'832','nombre_pais'=>'JERSEY','alfa2'=>'JE','alfa3'=>'JEY']);
        // $pais =Paises::create(['codigo_pais'=>'388','nombre_pais'=>'JAMAICA','alfa2'=>'JM','alfa3'=>'JAM']);
        // $pais =Paises::create(['codigo_pais'=>'400','nombre_pais'=>'JORDANIA','alfa2'=>'JO','alfa3'=>'JOR']);
        // $pais =Paises::create(['codigo_pais'=>'392','nombre_pais'=>'JAPÓN','alfa2'=>'JP','alfa3'=>'JPN']);
        // $pais =Paises::create(['codigo_pais'=>'404','nombre_pais'=>'KENIA','alfa2'=>'KE','alfa3'=>'KEN']);
        // $pais =Paises::create(['codigo_pais'=>'417','nombre_pais'=>'KIRGUISTÁN','alfa2'=>'KG','alfa3'=>'KGZ']);
        // $pais =Paises::create(['codigo_pais'=>'116','nombre_pais'=>'CAMBOYA','alfa2'=>'KH','alfa3'=>'KHM']);
        // $pais =Paises::create(['codigo_pais'=>'296','nombre_pais'=>'KIRIBATI','alfa2'=>'KI','alfa3'=>'KIR']);
        // $pais =Paises::create(['codigo_pais'=>'174','nombre_pais'=>'COMOROS','alfa2'=>'KM','alfa3'=>'COM']);
        // $pais =Paises::create(['codigo_pais'=>'659','nombre_pais'=>'SAN CRISTÓBAL Y NIEVES','alfa2'=>'KN','alfa3'=>'KNA']);
        // $pais =Paises::create(['codigo_pais'=>'408','nombre_pais'=>'COREA DEL NORTE','alfa2'=>'KP','alfa3'=>'PRK']);
        // $pais =Paises::create(['codigo_pais'=>'410','nombre_pais'=>'COREA DEL SUR','alfa2'=>'KR','alfa3'=>'KOR']);
        // $pais =Paises::create(['codigo_pais'=>'414','nombre_pais'=>'KUWAIT','alfa2'=>'KW','alfa3'=>'KWT']);
        // $pais =Paises::create(['codigo_pais'=>'136','nombre_pais'=>'ISLAS CAIMÁN','alfa2'=>'KY','alfa3'=>'CYM']);
        // $pais =Paises::create(['codigo_pais'=>'398','nombre_pais'=>'KAZAJSTÁN','alfa2'=>'KZ','alfa3'=>'KAZ']);
        // $pais =Paises::create(['codigo_pais'=>'418','nombre_pais'=>'LAOS','alfa2'=>'LA','alfa3'=>'LAO']);
        // $pais =Paises::create(['codigo_pais'=>'422','nombre_pais'=>'LÍBANO','alfa2'=>'LB','alfa3'=>'LBN']);
        // $pais =Paises::create(['codigo_pais'=>'662','nombre_pais'=>'SANTA LUCÍA','alfa2'=>'LC','alfa3'=>'LCA']);
        // $pais =Paises::create(['codigo_pais'=>'438','nombre_pais'=>'LIECHTENSTEIN','alfa2'=>'LI','alfa3'=>'LIE']);
        // $pais =Paises::create(['codigo_pais'=>'144','nombre_pais'=>'SRI LANKA','alfa2'=>'LK','alfa3'=>'LKA']);
        // $pais =Paises::create(['codigo_pais'=>'430','nombre_pais'=>'LIBERIA','alfa2'=>'LR','alfa3'=>'LBR']);
        // $pais =Paises::create(['codigo_pais'=>'426','nombre_pais'=>'LESOTHO','alfa2'=>'LS','alfa3'=>'LSO']);
        // $pais =Paises::create(['codigo_pais'=>'440','nombre_pais'=>'LITUANIA','alfa2'=>'LT','alfa3'=>'LTU']);
        // $pais =Paises::create(['codigo_pais'=>'442','nombre_pais'=>'LUXEMBURGO','alfa2'=>'LU','alfa3'=>'LUX']);
        // $pais =Paises::create(['codigo_pais'=>'428','nombre_pais'=>'LETONIA','alfa2'=>'LV','alfa3'=>'LVA']);
        // $pais =Paises::create(['codigo_pais'=>'434','nombre_pais'=>'LIBIA','alfa2'=>'LY','alfa3'=>'LBY']);
        // $pais =Paises::create(['codigo_pais'=>'504','nombre_pais'=>'MARRUECOS','alfa2'=>'MA','alfa3'=>'MAR']);
        // $pais =Paises::create(['codigo_pais'=>'492','nombre_pais'=>'MÓNACO','alfa2'=>'MC','alfa3'=>'MCO']);
        // $pais =Paises::create(['codigo_pais'=>'498','nombre_pais'=>'MOLDOVA','alfa2'=>'MD','alfa3'=>'MDA']);
        // $pais =Paises::create(['codigo_pais'=>'499','nombre_pais'=>'MONTENEGRO','alfa2'=>'ME','alfa3'=>'MNE']);
        // $pais =Paises::create(['codigo_pais'=>'450','nombre_pais'=>'MADAGASCAR','alfa2'=>'MG','alfa3'=>'MDG']);
        // $pais =Paises::create(['codigo_pais'=>'584','nombre_pais'=>'ISLAS MARSHALL','alfa2'=>'MH','alfa3'=>'MHL']);
        // $pais =Paises::create(['codigo_pais'=>'807','nombre_pais'=>'MACEDONIA','alfa2'=>'MK','alfa3'=>'MKD']);
        // $pais =Paises::create(['codigo_pais'=>'466','nombre_pais'=>'MALI','alfa2'=>'ML','alfa3'=>'MLI']);
        // $pais =Paises::create(['codigo_pais'=>'104','nombre_pais'=>'MYANMAR','alfa2'=>'MM','alfa3'=>'MMR']);
        // $pais =Paises::create(['codigo_pais'=>'496','nombre_pais'=>'MONGOLIA','alfa2'=>'MN','alfa3'=>'MNG']);
        // $pais =Paises::create(['codigo_pais'=>'446','nombre_pais'=>'MACAO','alfa2'=>'MO','alfa3'=>'MAC']);
        // $pais =Paises::create(['codigo_pais'=>'474','nombre_pais'=>'MARTINICA','alfa2'=>'MQ','alfa3'=>'MTQ']);
        // $pais =Paises::create(['codigo_pais'=>'478','nombre_pais'=>'MAURITANIA','alfa2'=>'MR','alfa3'=>'MRT']);
        // $pais =Paises::create(['codigo_pais'=>'500','nombre_pais'=>'MONTSERRAT','alfa2'=>'MS','alfa3'=>'MSR']);
        // $pais =Paises::create(['codigo_pais'=>'470','nombre_pais'=>'MALTA','alfa2'=>'MT','alfa3'=>'MLT']);
        // $pais =Paises::create(['codigo_pais'=>'480','nombre_pais'=>'MAURICIO','alfa2'=>'MU','alfa3'=>'MUS']);
        // $pais =Paises::create(['codigo_pais'=>'462','nombre_pais'=>'MALDIVAS','alfa2'=>'MV','alfa3'=>'MDV']);
        // $pais =Paises::create(['codigo_pais'=>'454','nombre_pais'=>'MALAWI','alfa2'=>'MW','alfa3'=>'MWI']);
        // $pais =Paises::create(['codigo_pais'=>'484','nombre_pais'=>'MÉXICO','alfa2'=>'MX','alfa3'=>'MEX']);
        // $pais =Paises::create(['codigo_pais'=>'458','nombre_pais'=>'MALASIA','alfa2'=>'MY','alfa3'=>'MYS']);
        // $pais =Paises::create(['codigo_pais'=>'508','nombre_pais'=>'MOZAMBIQUE','alfa2'=>'MZ','alfa3'=>'MOZ']);
        // $pais =Paises::create(['codigo_pais'=>'516','nombre_pais'=>'NAMIBIA','alfa2'=>'NA','alfa3'=>'NAM']);
        // $pais =Paises::create(['codigo_pais'=>'540','nombre_pais'=>'NUEVA CALEDONIA','alfa2'=>'NC','alfa3'=>'NCL']);
        // $pais =Paises::create(['codigo_pais'=>'562','nombre_pais'=>'NÍGER','alfa2'=>'NE','alfa3'=>'NER']);
        // $pais =Paises::create(['codigo_pais'=>'574','nombre_pais'=>'ISLAS NORKFOLK','alfa2'=>'NF','alfa3'=>'NFK']);
        // $pais =Paises::create(['codigo_pais'=>'566','nombre_pais'=>'NIGERIA','alfa2'=>'NG','alfa3'=>'NGA']);
        // $pais =Paises::create(['codigo_pais'=>'558','nombre_pais'=>'NICARAGUA','alfa2'=>'NI','alfa3'=>'NIC']);
        // $pais =Paises::create(['codigo_pais'=>'528','nombre_pais'=>'PAÍSES BAJOS','alfa2'=>'NL','alfa3'=>'NLD']);
        // $pais =Paises::create(['codigo_pais'=>'578','nombre_pais'=>'NORUEGA','alfa2'=>'NO','alfa3'=>'NOR']);
        // $pais =Paises::create(['codigo_pais'=>'524','nombre_pais'=>'NEPAL','alfa2'=>'NP','alfa3'=>'NPL']);
        // $pais =Paises::create(['codigo_pais'=>'520','nombre_pais'=>'NAURU','alfa2'=>'NR','alfa3'=>'NRU']);
        // $pais =Paises::create(['codigo_pais'=>'570','nombre_pais'=>'NIUE','alfa2'=>'NU','alfa3'=>'NIU']);
        // $pais =Paises::create(['codigo_pais'=>'554','nombre_pais'=>'NUEVA ZELANDA','alfa2'=>'NZ','alfa3'=>'NZL']);
        // $pais =Paises::create(['codigo_pais'=>'512','nombre_pais'=>'OMÁN','alfa2'=>'OM','alfa3'=>'OMN']);
        // $pais =Paises::create(['codigo_pais'=>'591','nombre_pais'=>'PANAMÁ','alfa2'=>'PA','alfa3'=>'PAN']);
        // $pais =Paises::create(['codigo_pais'=>'604','nombre_pais'=>'PERÚ','alfa2'=>'PE','alfa3'=>'PER']);
        // $pais =Paises::create(['codigo_pais'=>'258','nombre_pais'=>'POLINESIA FRANCESA','alfa2'=>'PF','alfa3'=>'PYF']);
        // $pais =Paises::create(['codigo_pais'=>'598','nombre_pais'=>'PAPÚA NUEVA GUINEA','alfa2'=>'PG','alfa3'=>'PNG']);
        // $pais =Paises::create(['codigo_pais'=>'608','nombre_pais'=>'FILIPINAS','alfa2'=>'PH','alfa3'=>'PHL']);
        // $pais =Paises::create(['codigo_pais'=>'586','nombre_pais'=>'PAKISTÁN','alfa2'=>'PK','alfa3'=>'PAK']);
        // $pais =Paises::create(['codigo_pais'=>'616','nombre_pais'=>'POLONIA','alfa2'=>'PL','alfa3'=>'POL']);
        // $pais =Paises::create(['codigo_pais'=>'666','nombre_pais'=>'SAN PEDRO Y MIQUELÓN','alfa2'=>'PM','alfa3'=>'SPM']);
        // $pais =Paises::create(['codigo_pais'=>'612','nombre_pais'=>'ISLAS PITCAIRN','alfa2'=>'PN','alfa3'=>'PCN']);
        // $pais =Paises::create(['codigo_pais'=>'630','nombre_pais'=>'PUERTO RICO','alfa2'=>'PR','alfa3'=>'PRI']);
        // $pais =Paises::create(['codigo_pais'=>'275','nombre_pais'=>'PALESTINA','alfa2'=>'PS','alfa3'=>'PSE']);
        // $pais =Paises::create(['codigo_pais'=>'620','nombre_pais'=>'PORTUGAL','alfa2'=>'PT','alfa3'=>'PRT']);
        // $pais =Paises::create(['codigo_pais'=>'585','nombre_pais'=>'ISLAS PALAOS','alfa2'=>'PW','alfa3'=>'PLW']);
        // $pais =Paises::create(['codigo_pais'=>'600','nombre_pais'=>'PARAGUAY','alfa2'=>'PY','alfa3'=>'PRY']);
        // $pais =Paises::create(['codigo_pais'=>'634','nombre_pais'=>'QATAR','alfa2'=>'QA','alfa3'=>'QAT']);
        // $pais =Paises::create(['codigo_pais'=>'638','nombre_pais'=>'REUNIÓN','alfa2'=>'RE','alfa3'=>'REU']);
        // $pais =Paises::create(['codigo_pais'=>'642','nombre_pais'=>'RUMANÍA','alfa2'=>'RO','alfa3'=>'ROU']);
        // $pais =Paises::create(['codigo_pais'=>'688','nombre_pais'=>'SERBIA Y MONTENEGRO','alfa2'=>'RS','alfa3'=>'SRB']);
        // $pais =Paises::create(['codigo_pais'=>'643','nombre_pais'=>'RUSIA','alfa2'=>'RU','alfa3'=>'RUS']);
        // $pais =Paises::create(['codigo_pais'=>'646','nombre_pais'=>'RUANDA','alfa2'=>'RW','alfa3'=>'RWA']);
        // $pais =Paises::create(['codigo_pais'=>'682','nombre_pais'=>'ARABIA SAUDITA','alfa2'=>'SA','alfa3'=>'SAU']);
        // $pais =Paises::create(['codigo_pais'=>'90','nombre_pais'=>'ISLAS SOLOMÓN','alfa2'=>'SB','alfa3'=>'SLB']);
        // $pais =Paises::create(['codigo_pais'=>'690','nombre_pais'=>'SEYCHELLES','alfa2'=>'SC','alfa3'=>'SYC']);
        // $pais =Paises::create(['codigo_pais'=>'736','nombre_pais'=>'SUDÁN','alfa2'=>'SD','alfa3'=>'SDN']);
        // $pais =Paises::create(['codigo_pais'=>'752','nombre_pais'=>'SUECIA','alfa2'=>'SE','alfa3'=>'SWE']);
        // $pais =Paises::create(['codigo_pais'=>'702','nombre_pais'=>'SINGAPUR','alfa2'=>'SG','alfa3'=>'SGP']);
        // $pais =Paises::create(['codigo_pais'=>'654','nombre_pais'=>'SANTA ELENA','alfa2'=>'SH','alfa3'=>'SHN']);
        // $pais =Paises::create(['codigo_pais'=>'705','nombre_pais'=>'ESLOVENIA','alfa2'=>'SI','alfa3'=>'SVN']);
        // $pais =Paises::create(['codigo_pais'=>'744','nombre_pais'=>'ISLAS SVALBARD Y JAN MAYEN','alfa2'=>'SJ','alfa3'=>'SJM']);
        // $pais =Paises::create(['codigo_pais'=>'703','nombre_pais'=>'ESLOVAQUIA','alfa2'=>'SK','alfa3'=>'SVK']);
        // $pais =Paises::create(['codigo_pais'=>'694','nombre_pais'=>'SIERRA LEONA','alfa2'=>'SL','alfa3'=>'SLE']);
        // $pais =Paises::create(['codigo_pais'=>'674','nombre_pais'=>'SAN MARINO','alfa2'=>'SM','alfa3'=>'SMR']);
        // $pais =Paises::create(['codigo_pais'=>'686','nombre_pais'=>'SENEGAL','alfa2'=>'SN','alfa3'=>'SEN']);
        // $pais =Paises::create(['codigo_pais'=>'706','nombre_pais'=>'SOMALIA','alfa2'=>'SO','alfa3'=>'SOM']);
        // $pais =Paises::create(['codigo_pais'=>'740','nombre_pais'=>'SURINAM','alfa2'=>'SR','alfa3'=>'SUR']);
        // $pais =Paises::create(['codigo_pais'=>'678','nombre_pais'=>'SANTO TOMÉ Y PRÍNCIPE','alfa2'=>'ST','alfa3'=>'STP']);
        // $pais =Paises::create(['codigo_pais'=>'222','nombre_pais'=>'EL SALVADOR','alfa2'=>'SV','alfa3'=>'SLV']);
        // $pais =Paises::create(['codigo_pais'=>'760','nombre_pais'=>'SIRIA','alfa2'=>'SY','alfa3'=>'SYR']);
        // $pais =Paises::create(['codigo_pais'=>'748','nombre_pais'=>'SUAZILANDIA','alfa2'=>'SZ','alfa3'=>'SWZ']);
        // $pais =Paises::create(['codigo_pais'=>'796','nombre_pais'=>'ISLAS TURCAS Y CAICOS','alfa2'=>'TC','alfa3'=>'TCA']);
        // $pais =Paises::create(['codigo_pais'=>'148','nombre_pais'=>'CHAD','alfa2'=>'TD','alfa3'=>'TCD']);
        // $pais =Paises::create(['codigo_pais'=>'260','nombre_pais'=>'TERRITORIOS AUSTRALES FRANCESES','alfa2'=>'TF','alfa3'=>'ATF']);
        // $pais =Paises::create(['codigo_pais'=>'768','nombre_pais'=>'TOGO','alfa2'=>'TG','alfa3'=>'TGO']);
        // $pais =Paises::create(['codigo_pais'=>'764','nombre_pais'=>'TAILANDIA','alfa2'=>'TH','alfa3'=>'THA']);
        // $pais =Paises::create(['codigo_pais'=>'834','nombre_pais'=>'TANZANIA','alfa2'=>'TH','alfa3'=>'TZA']);
        // $pais =Paises::create(['codigo_pais'=>'762','nombre_pais'=>'TAYIKISTÁN','alfa2'=>'TJ','alfa3'=>'TJK']);
        // $pais =Paises::create(['codigo_pais'=>'772','nombre_pais'=>'TOKELAU','alfa2'=>'TK','alfa3'=>'TKL']);
        // $pais =Paises::create(['codigo_pais'=>'626','nombre_pais'=>'TIMOR-LESTE','alfa2'=>'TL','alfa3'=>'TLS']);
        // $pais =Paises::create(['codigo_pais'=>'795','nombre_pais'=>'TURKMENISTÁN','alfa2'=>'TM','alfa3'=>'TKM']);
        // $pais =Paises::create(['codigo_pais'=>'788','nombre_pais'=>'TÚNEZ','alfa2'=>'TN','alfa3'=>'TUN']);
        // $pais =Paises::create(['codigo_pais'=>'776','nombre_pais'=>'TONGA','alfa2'=>'TO','alfa3'=>'TON']);
        // $pais =Paises::create(['codigo_pais'=>'792','nombre_pais'=>'TURQUÍA','alfa2'=>'TR','alfa3'=>'TUR']);
        // $pais =Paises::create(['codigo_pais'=>'780','nombre_pais'=>'TRINIDAD Y TOBAGO','alfa2'=>'TT','alfa3'=>'TTO']);
        // $pais =Paises::create(['codigo_pais'=>'798','nombre_pais'=>'TUVALU','alfa2'=>'TV','alfa3'=>'TUV']);
        // $pais =Paises::create(['codigo_pais'=>'158','nombre_pais'=>'TAIWÁN','alfa2'=>'TW','alfa3'=>'TWN']);
        // $pais =Paises::create(['codigo_pais'=>'804','nombre_pais'=>'UCRANIA','alfa2'=>'UA','alfa3'=>'UKR']);
        // $pais =Paises::create(['codigo_pais'=>'800','nombre_pais'=>'UGANDA','alfa2'=>'UG','alfa3'=>'UGA']);
        // $pais =Paises::create(['codigo_pais'=>'840','nombre_pais'=>'ESTADOS UNIDOS DE AMÉRICA','alfa2'=>'US','alfa3'=>'USA']);
        // $pais =Paises::create(['codigo_pais'=>'858','nombre_pais'=>'URUGUAY','alfa2'=>'UY','alfa3'=>'URY']);
        // $pais =Paises::create(['codigo_pais'=>'860','nombre_pais'=>'UZBEKISTÁN','alfa2'=>'UZ','alfa3'=>'UZB']);
        // $pais =Paises::create(['codigo_pais'=>'336','nombre_pais'=>'CIUDAD DEL VATICANO','alfa2'=>'VA','alfa3'=>'VAT']);
        // $pais =Paises::create(['codigo_pais'=>'670','nombre_pais'=>'SAN VICENTE Y LAS GRANADINAS','alfa2'=>'VC','alfa3'=>'VCT']);
        // $pais =Paises::create(['codigo_pais'=>'862','nombre_pais'=>'VENEZUELA','alfa2'=>'VE','alfa3'=>'VEN']);
        // $pais =Paises::create(['codigo_pais'=>'92','nombre_pais'=>'ISLAS VÍRGENES BRITÁNICAS','alfa2'=>'VG','alfa3'=>'VGB']);
        // $pais =Paises::create(['codigo_pais'=>'850','nombre_pais'=>'ISLAS VÍRGENES DE LOS ESTADOS UNIDOS DE AMÉRICA','alfa2'=>'VI','alfa3'=>'VIR']);
        // $pais =Paises::create(['codigo_pais'=>'704','nombre_pais'=>'VIETNAM','alfa2'=>'VN','alfa3'=>'VNM']);
        // $pais =Paises::create(['codigo_pais'=>'548','nombre_pais'=>'VANUATU','alfa2'=>'VU','alfa3'=>'VUT']);
        // $pais =Paises::create(['codigo_pais'=>'876','nombre_pais'=>'WALLIS Y FUTUNA','alfa2'=>'WF','alfa3'=>'WLF']);
        // $pais =Paises::create(['codigo_pais'=>'882','nombre_pais'=>'SAMOA','alfa2'=>'WS','alfa3'=>'WSM']);
        // $pais =Paises::create(['codigo_pais'=>'887','nombre_pais'=>'YEMEN','alfa2'=>'YE','alfa3'=>'YEM']);
        // $pais =Paises::create(['codigo_pais'=>'175','nombre_pais'=>'MAYOTTE','alfa2'=>'YT','alfa3'=>'MYT']);
        // $pais =Paises::create(['codigo_pais'=>'710','nombre_pais'=>'SUDÁFRICA','alfa2'=>'ZA','alfa3'=>'ZAF']);

    }
}
